"""
build_pptx_v3.py
----------------
Deterministic PPTX builder for AI Analyst slide decks.

Reads  : data/pipeline/{stem}/story_arc.json
         data/pipeline/{stem}/chart_images.json  (optional)
Writes : data/reports/{report_type}/{stem}/slidedeck.pptx
           (default report_type derived from stem)

Usage:
    python3 scripts/build_pptx_v3.py --stem sales_orders_2023_2026
    python3 scripts/build_pptx_v3.py --stem sales_orders_2023_2026 \
        --output data/reports/sales/sales_orders_2023_2026/slidedeck.pptx

All layout coordinates are HARDCODED — never generated by an LLM.
The LLM only produces story_arc.json content.
"""

from __future__ import annotations

import argparse
import copy
import io
import json
import os
import sys
import traceback
from pathlib import Path

# Fix Windows console encoding
if sys.stdout.encoding and sys.stdout.encoding.lower() not in ('utf-8', 'utf8'):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

# Structured logging
sys.path.insert(0, str(Path(__file__).parent.parent))
from helpers.utils.logger import get_logger, new_run_id

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.oxml.ns import qn
from lxml import etree

# ---------------------------------------------------------------------------
# Fixed paths
# ---------------------------------------------------------------------------
BASE = Path(__file__).parent.parent          # ai_analyst/
TEMPLATE_PATH = BASE / "templates/pptx_report/pptx_report_template.pptx"

def PIPELINE_DIR(stem: str) -> Path:
    return BASE / f"data/pipeline/{stem}"

def REPORTS_DIR(stem: str, rtype: str) -> Path:
    return BASE / f"data/reports/{rtype}/{stem}"


# ---------------------------------------------------------------------------
# Color / unit helpers
# ---------------------------------------------------------------------------
def rgb(hex_str: str) -> RGBColor:
    h = hex_str.lstrip("#")
    return RGBColor(int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))

def in_(val: float) -> Emu:
    return Inches(val)

def pt_(val: float) -> Emu:
    return Pt(val)


# ---------------------------------------------------------------------------
# Color palette
# ---------------------------------------------------------------------------
C = {
    "cover_bg":      "#0F1729",
    "content_bg":    "#F5F5F0",
    "panel_bg":      "#FFFFFF",
    "kpi_sep":       "#1E293B",
    "divider":       "#E2E8F0",
    "text_primary":  "#111827",
    "text_body":     "#374151",
    "text_secondary":"#64748B",
    "text_muted":    "#94A3B8",
    "text_cover_bc": "#475569",
    "text_kpi_label":"#334155",
    "text_kpi_value":"#94A3B8",
    "white":         "#FFFFFF",
    "blue":          "#2554E7",
    "orange":        "#F97316",
    "red":           "#EF4444",
    "green":         "#22C55E",
    "teal":          "#42967A",
    "teal_light":    "#E6F5EF",
    "blue_light":    "#EEF2FF",
    "red_light":     "#FFF5F5",
}

# Module-level logger (used by helper functions before run_id is known)
_log = get_logger(__name__)

SECTION_ACCENT = {
    "context":    "#2554E7",
    "tension":    "#EF4444",
    "findings":   "#EF4444",
    "resolution": "#42967A",
    "action":     "#42967A",
    "appendix":   "#94A3B8",
    "predictive": "#EF4444",
    "diagnostic": "#EF4444",
    "conclusions":"#2554E7",
}


# ---------------------------------------------------------------------------
# Presentation initialisation (CRITICAL pattern)
# ---------------------------------------------------------------------------
def init_presentation() -> tuple[Presentation, object]:
    """Load template, strip all existing slides, return (prs, BLANK_LAYOUT)."""
    prs = Presentation(str(TEMPLATE_PATH))
    # Remove all existing template slides safely via XML
    sldIdLst = prs.slides._sldIdLst
    for sld_id in list(sldIdLst.sldId_lst):
        rId = sld_id.get('{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id')
        if rId:
            try:
                prs.part.drop_rel(rId)
            except Exception as e:
                _log.debug("drop_rel_failed", rId=rId, error=str(e))
        sldIdLst.remove(sld_id)
    BLANK_LAYOUT = prs.slide_layouts[6]
    return prs, BLANK_LAYOUT


# ---------------------------------------------------------------------------
# Visual helpers & Markdown parser
# ---------------------------------------------------------------------------
import re

def clean_bold_separators(text: str) -> str:
    """
    Remove ':' or '—' immediately following markdown double asterisks '**' or similar bold boundaries.
    Example: '**Overall performance**: Q1...' -> '**Overall performance** Q1...'
             '**Overall performance** — Q1...' -> '**Overall performance** Q1...'
             '**Overall performance** : Q1...' -> '**Overall performance** Q1...'
    """
    if not text:
        return text
    # Match bold prefix and trailing horizontal spaces + separator + optional horizontal spaces
    # on the same line (using [ \t] instead of \s to avoid swallowing newlines/bullet dashes)
    cleaned = re.sub(r'(\*\*[^*]+\*\*)(?:[ \t]*[:\-—–·][ \t]*)(?=[ \t]*\w)', r'\1 ', text)
    cleaned = re.sub(r'(\*\*[^*]+\*\*)(?:[ \t]*[:\-—–·][ \t]*)$', r'\1', cleaned)
    return cleaned

def clear_shape_shadow(shape):
    """Remove any shadow effect from a shape's spPr effectLst."""
    try:
        sp = shape._element
        spPr = sp.find(qn("p:spPr"))
        if spPr is None:
            spPr = sp.find(qn("a:spPr"))
        if spPr is None:
            return
        effect_lst = spPr.find(qn("a:effectLst"))
        if effect_lst is not None:
            # Remove outerShdw / innerShdw / glowEffect children
            for tag in ("a:outerShdw", "a:innerShdw", "a:glow", "a:reflection"):
                el = effect_lst.find(qn(tag))
                if el is not None:
                    effect_lst.remove(el)
        # Also clear effectDag if present
        effect_dag = spPr.find(qn("a:effectDag"))
        if effect_dag is not None:
            spPr.remove(effect_dag)
    except Exception as e:
        _log.debug("clear_shadow_failed", shape=getattr(shape, "name", "?"), error=str(e))


def clear_slide_shadows(slide):
    """Remove shadow effects from every shape on a slide."""
    for shape in slide.shapes:
        clear_shape_shadow(shape)


def set_shape_dash_style(shape, style_name: str = "sysDot"):
    """Set preset dash style for shape outline using OpenXML."""
    try:
        spPr = shape._element.spPr
        ln = spPr.find(qn("a:ln"))
        if ln is not None:
            prstDash = ln.find(qn("a:prstDash"))
            if prstDash is not None:
                ln.remove(prstDash)
            new_dash = etree.SubElement(ln, qn("a:prstDash"))
            new_dash.set("val", style_name)
    except Exception as e:
        _log.warning("dash_style_failed", style=style_name, error=str(e))


def _set_panel_border(shape):
    """Set themed dashed border on a panel: tx1 (dark) scheme color + sysDash."""
    try:
        spPr = shape._element.spPr
        ln = spPr.find(qn("a:ln"))
        if ln is not None:
            spPr.remove(ln)
        ln = etree.SubElement(spPr, qn("a:ln"))
        solidFill = etree.SubElement(ln, qn("a:solidFill"))
        schemeClr = etree.SubElement(solidFill, qn("a:schemeClr"))
        schemeClr.set("val", "tx1")
        prstDash = etree.SubElement(ln, qn("a:prstDash"))
        prstDash.set("val", "sysDash")
        if spPr.find(qn("a:effectLst")) is None:
            etree.SubElement(spPr, qn("a:effectLst"))
    except Exception as e:
        _log.warning("panel_border_failed", error=str(e))
def _apply_native_bullet(para, char: str = "•", indent_inches: float = 0.20):
    """Apply native PowerPoint bullet character to a paragraph via OpenXML."""
    try:
        pPr = para._p.get_or_add_pPr()
        # Remove any existing buNone
        for tag in ("a:buNone", "a:buChar", "a:buAutoNum", "a:buFont"):
            el = pPr.find(qn(tag))
            if el is not None:
                pPr.remove(el)
        # Set indent + hanging indent for clean bullet layout
        pPr.set("indent", str(-int(Inches(indent_inches))))
        pPr.set("marL", str(int(Inches(indent_inches))))
        # Bullet font
        buFont = etree.SubElement(pPr, qn("a:buFont"))
        buFont.set("typeface", "Arial")
        buFont.set("charset", "0")
        # Bullet character
        buChar = etree.SubElement(pPr, qn("a:buChar"))
        buChar.set("char", char)
    except Exception as e:
        _log.debug("native_bullet_failed", char=char, error=str(e))


def add_markdown_text(slide, text: str, x: float, y: float, w: float, h: float,
                      font_name: str = "Calibri", font_size: float = 12,
                      default_bold: bool = False, italic: bool = False,
                      color_hex: str = "#111827", align=PP_ALIGN.LEFT,
                      word_wrap: bool = True,
                      native_bullets: bool = False) -> object:
    """
    Parses multi-line text, detects indented bullet list syntax (e.g. starting with '-' or '  -'),
    formats bold runs using markdown '**', and adds paragraphs cleanly to a single textbox.
    """
    txBox = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = txBox.text_frame
    tf.word_wrap = word_wrap
    tf.margin_left = Inches(0)
    tf.margin_right = Inches(0)
    tf.margin_top = Inches(0)
    tf.margin_bottom = Inches(0)

    if not text:
        return txBox

    # Clean bold separators and split into lines
    text_cleaned = clean_bold_separators(text)
    lines = text_cleaned.split("\n")
    
    first_non_empty = True
    
    for line in lines:
        if not line.strip():
            continue
            
        if first_non_empty:
            p = tf.paragraphs[0]
            first_non_empty = False
        else:
            p = tf.add_paragraph()
            
        p.alignment = align
        
        # Bullet detection
        stripped = line.strip()
        is_sub_bullet = line.startswith("  -") or line.startswith("    -") or line.startswith("  *") or line.startswith("    *")
        is_main_bullet = (line.startswith("-") or line.startswith("*") or line.startswith("•")) and not is_sub_bullet
        
        # Configure native PowerPoint paragraph indentation and spacing
        if is_sub_bullet:
            p.level = 1
            p.space_before = Pt(2)
            p.space_after = Pt(2)
            text_to_parse = stripped
        elif is_main_bullet:
            p.level = 0
            p.space_before = Pt(3)
            p.space_after = Pt(3)
            text_to_parse = stripped
        else:
            p.level = 0
            p.space_before = Pt(6)
            p.space_after = Pt(3)
            text_to_parse = stripped

        # Apply native bullet if requested (every non-empty paragraph gets a bullet dot)
        if native_bullets:
            _apply_native_bullet(p)
            
        # Parse double-asterisk bold runs within this paragraph
        parts = text_to_parse.split("**")
        for idx, part in enumerate(parts):
            if not part:
                continue
            run = p.add_run()
            run.text = part
            run.font.name = font_name
            run.font.size = Pt(font_size)
            run.font.bold = (idx % 2 == 1) or default_bold
            run.font.italic = italic
            run.font.color.rgb = rgb(color_hex)
            
    return txBox


# ---------------------------------------------------------------------------
# Low-level shape primitives
# ---------------------------------------------------------------------------
def add_rect(slide, x: float, y: float, w: float, h: float,
             fill_hex: str | None = None, line_hex: str | None = None,
             line_width: float = 0, corner_radius: int = 0):
    """Add a rectangle. fill_hex=None → transparent (no fill)."""
    shape = slide.shapes.add_shape(
        1,  # MSO_SHAPE_TYPE.RECTANGLE
        Inches(x), Inches(y), Inches(w), Inches(h)
    )
    # Large white/panel shapes → transparent fill + themed dashed border (matches reference design)
    is_panel = (fill_hex in ("#FFFFFF", C["panel_bg"])) and (w > 1.0 and h > 1.0)
    if is_panel:
        fill_hex = None  # transparent fill, delineated by border only

    if fill_hex is None:
        shape.fill.background()          # transparent
    else:
        shape.fill.solid()
        shape.fill.fore_color.rgb = rgb(fill_hex)

    if is_panel:
        _set_panel_border(shape)         # tx1 scheme color + sysDash
    elif line_hex and line_width > 0:
        shape.line.color.rgb = rgb(line_hex)
        shape.line.width = Pt(line_width)
        set_shape_dash_style(shape, "sysDot")
    else:
        shape.line.fill.background()     # no border

    # Unify all standard card panels to 1413 adjustments for a clean modern corner radius
    if 0 < corner_radius < 50000:
        corner_radius = 1413

    if corner_radius > 0:
        sp = shape._element
        spPr = sp.find(qn("p:spPr"))
        prstGeom = spPr.find(qn("a:prstGeom"))
        if prstGeom is None:
            custGeom = spPr.find(qn("a:custGeom"))
            if custGeom is not None:
                spPr.remove(custGeom)
            prstGeom = etree.SubElement(spPr, qn("a:prstGeom"))
            prstGeom.set("prst", "roundRect")
            avLst = etree.SubElement(prstGeom, qn("a:avLst"))
            gd = etree.SubElement(avLst, qn("a:gd"))
            gd.set("name", "adj")
            gd.set("fmla", f"val {corner_radius}")
        else:
            prstGeom.set("prst", "roundRect")
            avLst = prstGeom.find(qn("a:avLst"))
            if avLst is None:
                avLst = etree.SubElement(prstGeom, qn("a:avLst"))
            gd = avLst.find(qn("a:gd"))
            if gd is None:
                gd = etree.SubElement(avLst, qn("a:gd"))
            gd.set("name", "adj")
            gd.set("fmla", f"val {corner_radius}")
    return shape


def add_oval(slide, x: float, y: float, w: float, h: float, fill_hex: str):
    """Add a circle / oval shape."""
    from pptx.enum.shapes import MSO_SHAPE_TYPE
    shape = slide.shapes.add_shape(
        9,  # MSO_AUTO_SHAPE_TYPE.OVAL
        Inches(x), Inches(y), Inches(w), Inches(h)
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = rgb(fill_hex)
    shape.line.fill.background()
    return shape


def add_text(slide, text: str, x: float, y: float, w: float, h: float,
             font_name: str = "Calibri", font_size: float = 12,
             bold: bool = False, italic: bool = False,
             color_hex: str = "#111827", align=PP_ALIGN.LEFT,
             word_wrap: bool = True) -> object:
    """Add a plain text box."""
    txBox = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = txBox.text_frame
    tf.word_wrap = word_wrap
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = str(text)
    run.font.name = font_name
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = rgb(color_hex)
    return txBox


def add_rich_text(slide, segments: list, x: float, y: float, w: float, h: float,
                  font_name: str = "Calibri", font_size: float = 12,
                  word_wrap: bool = True) -> object:
    """
    segments = list of (text, bold, color_hex).
    All segments appear on the same paragraph (one text box, mixed formatting).
    """
    txBox = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = txBox.text_frame
    tf.word_wrap = word_wrap
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.LEFT
    for (text, bold, color_hex) in segments:
        run = p.add_run()
        run.text = str(text)
        run.font.name = font_name
        run.font.size = Pt(font_size)
        run.font.bold = bold
        run.font.color.rgb = rgb(color_hex)
    return txBox


def add_image(slide, img_path: str | Path, x: float, y: float, w: float, h: float):
    """Add PNG image. If path not found, add gray placeholder rect."""
    img_path = Path(img_path)
    if img_path.exists():
        try:
            slide.shapes.add_picture(
                str(img_path),
                Inches(x), Inches(y), Inches(w), Inches(h)
            )
            return
        except Exception as e:
            _log.warning("image_embed_failed", img=str(img_path), error=str(e))
    # Placeholder
    add_rect(slide, x, y, w, h, fill_hex="#D1D5DB")
    add_text(slide, "[chart not found]", x + 0.1, y + h / 2 - 0.15, w - 0.2, 0.3,
             font_size=9, color_hex="#6B7280", align=PP_ALIGN.CENTER)


def add_slide(prs, blank_layout) -> object:
    """Add blank slide using BLANK_LAYOUT."""
    return prs.slides.add_slide(blank_layout)


# ---------------------------------------------------------------------------
# Universal header components
# ---------------------------------------------------------------------------
def add_bg(slide, hex_color: str = "#F5F5F0"):
    """Full slide background rect (0,0) 13.33×7.50."""
    add_rect(slide, 0, 0, 13.33, 7.50, fill_hex=hex_color)


def add_breadcrumb(slide, section: str, topic: str, section_color: str):
    """Breadcrumb at (0.89, 0.41). Section in #94A3B8, ' | Topic' in section_color bold."""
    txBox = slide.shapes.add_textbox(Inches(0.89), Inches(0.41), Inches(8.0), Inches(0.27))
    tf = txBox.text_frame
    tf.word_wrap = False
    p = tf.paragraphs[0]

    r1 = p.add_run()
    r1.text = section + "  |  "
    r1.font.name = "Calibri Light"
    r1.font.size = Pt(10)
    r1.font.bold = False
    r1.font.color.rgb = rgb("#94A3B8")

    r2 = p.add_run()
    r2.text = topic
    r2.font.name = "Calibri"
    r2.font.size = Pt(10)
    r2.font.bold = True
    r2.font.color.rgb = rgb(section_color)


def add_headline(slide, text: str, accent_phrases: list | None = None,
                 accent_color: str = "#111827"):
    """
    Headline at (0.89, 0.68) 11.56×0.77". Calibri 20pt bold #111827.
    accent_phrases: list of substrings to color with accent_color (bold).
    """
    text = clean_bold_separators(text)
    if not accent_phrases:
        add_text(slide, text, 0.89, 0.68, 11.56, 0.77,
                 font_name="Calibri", font_size=20, bold=True, color_hex="#111827", word_wrap=True)
        return

    # Build segments with accent coloring
    remaining = str(text)
    segments: list = []
    for phrase in (accent_phrases or []):
        idx = remaining.find(phrase)
        if idx == -1:
            continue
        if idx > 0:
            segments.append((remaining[:idx], True, "#111827"))
        segments.append((phrase, True, accent_color))
        remaining = remaining[idx + len(phrase):]
    if remaining:
        segments.append((remaining, True, "#111827"))
    if not segments:
        segments = [(text, True, "#111827")]
    add_rich_text(slide, segments, 0.89, 0.68, 11.56, 0.77,
                  font_name="Calibri", font_size=20, word_wrap=True)


def add_slide_number(slide, number: int | str):
    """Slide number at (12.3, 7.10). Calibri 9pt #94A3B8."""
    add_text(slide, str(number), 12.3, 7.10, 0.8, 0.3,
             font_size=9, color_hex="#94A3B8", align=PP_ALIGN.RIGHT)


def _parse_breadcrumb(raw: str) -> tuple[str, str]:
    """Split 'Section  |  Topic' or fallback."""
    for sep in ("  |  ", " | ", "|"):
        if sep in raw:
            parts = raw.split(sep, 1)
            return parts[0].strip(), parts[1].strip()
    return raw.strip(), ""


def _section_accent(slide_data: dict) -> str:
    section = slide_data.get("section", "context").lower()
    return SECTION_ACCENT.get(section, C["blue"])


def _standard_header(slide, slide_data: dict):
    """Apply breadcrumb + headline + slide number (no background rect — relies on master)."""
    accent = _section_accent(slide_data)
    bc_raw = slide_data.get("breadcrumb", "")
    if not bc_raw:
        bs = slide_data.get("breadcrumb_section", "")
        bt = slide_data.get("breadcrumb_topic", "")
        if bs and bt:
            bc_raw = f"{bs}  |  {bt}"
        elif bs or bt:
            bc_raw = bs or bt
    if bc_raw:
        sec, topic = _parse_breadcrumb(bc_raw)
        add_breadcrumb(slide, sec, topic, accent)
    headline = slide_data.get("headline", "")
    # Support both field names: accent_phrases (legacy) and headline_accents (story_arc.json)
    accent_phrases = slide_data.get("accent_phrases") or slide_data.get("headline_accents", [])
    add_headline(slide, headline, accent_phrases=accent_phrases or None,
                 accent_color=accent)
    num = slide_data.get("slide_number", "")
    if num:
        add_slide_number(slide, num)


# ---------------------------------------------------------------------------
# Chart path resolver (module-level, set in build_pptx)
# ---------------------------------------------------------------------------
_chart_map: dict = {}
_chart_dir: Path = Path(".")

def _resolve_chart(chart_id: str | None) -> Path | None:
    if not chart_id:
        return None
    rel = _chart_map.get(chart_id)
    if rel:
        p = BASE / rel
        if p.exists():
            return p
    # Fallback: look in chart_images folder
    fallback = _chart_dir / f"{chart_id}.png"
    if fallback.exists():
        return fallback
    return None


# ---------------------------------------------------------------------------
# Layout builders
# ---------------------------------------------------------------------------

def build_cover(prs, blank_layout, slide_data: dict):
    """COVER — dark navy title slide."""
    slide = add_slide(prs, blank_layout)
    add_bg(slide, C["cover_bg"])

    title_upper = slide_data.get("title", "AI ANALYST").upper()
    project_label = f"AI ANALYST  ·  {title_upper}"
    add_text(slide, project_label, 0.89, 0.38, 11.0, 0.25,
             font_name="Calibri Light", font_size=10, bold=False, color_hex=C["text_cover_bc"])

    # Blue accent bar
    add_rect(slide, 0.89, 1.95, 0.55, 0.05, fill_hex=C["blue"])

    # Headline (28pt white bold)
    headline = slide_data.get("headline", "")
    add_text(slide, headline, 0.89, 2.05, 8.50, 0.40,
             font_name="Calibri", font_size=28, bold=True, color_hex=C["white"], word_wrap=True)

    # Subtitle — from left_panel.supporting_text
    left_panel = slide_data.get("left_panel") or {}
    subtitle = left_panel.get("supporting_text", slide_data.get("subtitle", ""))
    add_text(slide, subtitle, 0.89, 4.70, 9.00, 0.40,
             font_name="Calibri Light", font_size=13, bold=False, color_hex=C["text_secondary"], word_wrap=True)

    # KPI separators (vertical bars)
    for sx in [3.19, 5.50, 7.82, 10.13]:
        add_rect(slide, sx, 6.25, 0.01, 1.00, fill_hex=C["kpi_sep"])

    # KPI data: up to 5 from cover_kpis, last one always "PREPARED BY / AI Analyst"
    kpis = list(slide_data.get("cover_kpis", []))
    # Ensure we have exactly 5 entries
    while len(kpis) < 4:
        kpis.append({"label": "", "value": ""})
    kpis = kpis[:4]
    kpis.append({"label": "PREPARED BY", "value": "AI Analyst"})

    kpi_x = [0.89, 3.20, 5.51, 7.83, 10.14]
    for i, kpi in enumerate(kpis[:5]):
        x = kpi_x[i]
        add_text(slide, kpi.get("label", ""), x, 6.33, 2.31, 0.22,
                 font_name="Calibri Light", font_size=9, bold=False, color_hex=C["text_kpi_label"])
        add_text(slide, kpi.get("value", ""), x, 6.57, 2.31, 0.40,
                 font_name="Calibri", font_size=16, bold=True, color_hex=C["text_kpi_value"])

    return slide


def build_background(prs, blank_layout, slide_data: dict):
    """BACKGROUND — business context + scope."""
    slide = add_slide(prs, blank_layout)
    _standard_header(slide, slide_data)

    content = slide_data.get("content", {})
    left_panel = slide_data.get("left_panel", content.get("left_panel", {}))
    right_panel = slide_data.get("right_panel", content.get("right_panel", {}))

    left_title  = left_panel.get("title",  "Business Context")
    right_title = right_panel.get("title", "Analysis Scope")

    # Left panel background
    add_rect(slide, 0.89, 1.59, 5.55, 5.10, fill_hex=C["panel_bg"], corner_radius=2000)

    # Left panel title
    add_text(slide, left_title, 0.97, 1.72, 5.30, 0.34,
             font_name="Calibri", font_size=14, bold=True, color_hex=C["blue"])

    # Body text — extends from below title (y=2.13) to just above KEY QUESTION (y=5.50)
    body_text = left_panel.get("supporting_text", left_panel.get("body", ""))
    add_markdown_text(slide, body_text, 0.97, 2.13, 5.30, 3.37,
                      font_name="Calibri Light", font_size=11, color_hex=C["text_body"], word_wrap=True)

    # KEY QUESTION box (only draw if explicitly provided in slide_data or left_panel)
    key_q = left_panel.get("key_question") or slide_data.get("key_question")
    if key_q:
        add_rect(slide, 1.06, 5.63, 5.21, 0.85, fill_hex=C["blue"], corner_radius=2000)
        add_text(slide, "KEY QUESTION", 1.15, 5.70, 5.00, 0.25,
                 font_name="Calibri", font_size=9, bold=True, color_hex=C["white"])
        add_markdown_text(slide, key_q, 1.15, 5.96, 5.00, 0.45,
                          font_name="Calibri Light", font_size=11, color_hex=C["white"], word_wrap=True)

    # Right panel background
    add_rect(slide, 6.89, 1.59, 5.55, 5.10, fill_hex=C["panel_bg"], corner_radius=2000)

    # Right panel title
    add_text(slide, right_title, 6.98, 1.72, 5.30, 0.34,
             font_name="Calibri", font_size=14, bold=True, color_hex=C["blue"])

    # 4 scope rows — try cards[], else auto-build from pipeline_state.json
    scope_rows_y = [2.20, 3.16, 4.11, 5.07]
    cards = right_panel.get("cards", [])
    if not cards:
        # Auto-generate scope cards from pipeline metadata
        stem_meta = {}
        try:
            import json as _json
            state_path = BASE / f"data/pipeline/{slide_data.get('_stem', '')}/pipeline_state.json"
            if state_path.exists():
                with open(state_path) as _f:
                    loaded = _json.load(_f)
                    # pipeline_state.json stores data at top level (no run_context wrapper)
                    stem_meta = loaded.get("run_context", loaded)
        except Exception as e:
            _log.warning("scope_meta_load_failed", error=str(e))
        date_range  = stem_meta.get("date_range", "—")
        if isinstance(date_range, dict):
            date_range = f"{date_range.get('start_date', '—')} to {date_range.get('end_date', '—')}"
        row_count   = stem_meta.get("row_count", "—")
        cols        = stem_meta.get("columns", [])
        dims        = ", ".join(c for c in cols if c not in ("revenue", "quantity",
                                "discount_rate", "churn_flag", "order_date",
                                "customer_id")) if cols else "—"
        cards = [
            {"label": "DATA PERIOD",      "value": str(date_range)},
            {"label": "RECORDS ANALYZED", "value": f"{row_count} orders"},
            {"label": "DIMENSIONS",        "value": str(dims)},
            {"label": "METHODS",           "value": "Descriptive, Diagnostic, Predictive"},
        ]
    for i, row_y in enumerate(scope_rows_y):
        if i < len(cards):
            card  = cards[i]
            label = card.get("label", card.get("number", ""))
            value = card.get("value", card.get("title", ""))
        else:
            label = ""
            value = ""
        # Badge circle (no number text inside — matches reference design)
        add_rect(slide, 7.28, row_y + 0.14, 0.35, 0.35, fill_hex=C["blue"], corner_radius=80000)
        
        # Label and value texts
        add_text(slide, label, 7.78, row_y + 0.06, 4.50, 0.22,
                 font_name="Calibri", font_size=9, bold=True, color_hex=C["text_kpi_label"])
        add_markdown_text(slide, value, 7.78, row_y + 0.26, 4.50, 0.30,
                          font_name="Calibri Light", font_size=10, color_hex=C["text_primary"], word_wrap=True)

    return slide


def build_insight_chart(prs, blank_layout, slide_data: dict):
    """
    INSIGHT_CHART — primary two-panel analysis layout.
    Implements the Pyramid Principle: Conclusion → Evidence → Data.
    """
    slide = add_slide(prs, blank_layout)
    _standard_header(slide, slide_data)

    accent = _section_accent(slide_data)
    content = slide_data.get("content", {})
    left_panel  = slide_data.get("left_panel",  content.get("left_panel",  {}))
    right_panel = slide_data.get("right_panel", content.get("right_panel", {}))

    # Detect single-chart mode: only left panel has a chart, right has text only
    left_has_chart  = bool(left_panel.get("chart_id") or slide_data.get("chart_id"))
    right_has_chart = bool(right_panel.get("chart_id"))
    single_chart    = left_has_chart and not right_has_chart and bool(right_panel.get("supporting_text"))

    panels = [
        (left_panel,  0.89, "1"),
        (right_panel, 6.89, "2"),
    ]

    for panel_data, px, panel_num in panels:
        if not panel_data:
            continue

        # Single-chart mode: right panel is wider text area, no chart container
        if single_chart and panel_num == "2":
            add_rect(slide, px, 1.64, 5.55, 5.26, fill_hex=C["panel_bg"], corner_radius=8000)
            add_oval(slide, px + 0.16, 1.83, 0.26, 0.26, fill_hex=accent)
            add_text(slide, panel_num, px + 0.16, 1.83, 0.26, 0.26,
                     font_name="Calibri", font_size=9, bold=True, color_hex=C["white"], align=PP_ALIGN.CENTER)
            st = panel_data.get("supporting_text", panel_data.get("body", ""))
            add_markdown_text(slide, st, px + 0.16, 2.14, 5.23, 4.60,
                              font_name="Calibri Light", font_size=11, color_hex=C["text_body"], word_wrap=True)
            continue

        # Panel background
        add_rect(slide, px, 1.64, 5.55, 5.26, fill_hex=C["panel_bg"], corner_radius=8000)

        # Quote badge (oval) with panel number
        add_oval(slide, px + 0.16, 1.83, 0.26, 0.26, fill_hex=accent)
        add_text(slide, panel_num, px + 0.16, 1.83, 0.26, 0.26,
                 font_name="Calibri", font_size=9, bold=True, color_hex=C["white"], align=PP_ALIGN.CENTER)

        # Supporting text with accent phrases
        supporting_text = panel_data.get("supporting_text", panel_data.get("body", ""))
        supporting_text = clean_bold_separators(supporting_text)
        supporting_accents = panel_data.get("supporting_accents", [])
        if supporting_accents:
            remaining = str(supporting_text)
            segs: list = []
            for phrase in supporting_accents:
                idx = remaining.find(phrase)
                if idx == -1:
                    continue
                if idx > 0:
                    segs.append((remaining[:idx], False, C["text_body"]))
                segs.append((phrase, True, accent))
                remaining = remaining[idx + len(phrase):]
            if remaining:
                segs.append((remaining, False, C["text_body"]))
            if segs:
                add_rich_text(slide, segs, px + 0.16, 2.14, 5.23, 0.90,
                              font_name="Calibri Light", font_size=11, word_wrap=True)
            else:
                add_markdown_text(slide, supporting_text, px + 0.16, 2.14, 5.23, 0.90,
                                  font_name="Calibri Light", font_size=11, color_hex=C["text_body"], word_wrap=True)
        else:
            add_markdown_text(slide, supporting_text, px + 0.16, 2.14, 5.23, 0.90,
                              font_name="Calibri Light", font_size=11, color_hex=C["text_body"], word_wrap=True)

        # Chart section
        chart_id   = panel_data.get("chart_id")
        chart_title = panel_data.get("chart_title", "")

        # Also check slide-level chart_id for left panel only
        if not chart_id and px == 0.89:
            chart_id = slide_data.get("chart_id")
            chart_title = chart_title or slide_data.get("chart_title", "")

        if chart_id or chart_title:
            # Chart container (transparent rounded rect)
            add_rect(slide, px + 0.16, 3.23, 5.23, 3.47,
                     fill_hex=None, corner_radius=10000)
            # Chart title
            if chart_title:
                add_text(slide, chart_title, px + 0.29, 3.35, 4.93, 0.28,
                         font_name="Calibri", font_size=10.5, bold=True, color_hex=C["text_body"])
            # Chart image
            chart_path = _resolve_chart(chart_id)
            if chart_path:
                add_image(slide, chart_path, px + 0.29, 3.74, 4.93, 2.78)
            else:
                add_rect(slide, px + 0.29, 3.74, 4.93, 2.78, fill_hex="#D1D5DB")
        elif not chart_id:
            # No chart — extend supporting text downward
            add_markdown_text(slide, supporting_text, px + 0.16, 2.14, 5.23, 4.60,
                              font_name="Calibri Light", font_size=12, color_hex=C["text_body"], word_wrap=True)

    return slide


def _three_col_cards(prs, blank_layout, slide_data: dict,
                     badge_bg: str, badge_num_color: str,
                     title_color: str, title_bold: bool,
                     footer_fill: str, footer_text_color: str):
    """
    Shared renderer for FINDINGS_OVERVIEW, CONCLUSIONS_OVERVIEW, STRATEGY_MAPS.
    All share the same x/y positions; only badge/title/footer colours differ.
    """
    slide = add_slide(prs, blank_layout)
    _standard_header(slide, slide_data)

    content = slide_data.get("content", {})
    cards = content.get("cards", slide_data.get("cards", []))
    col_x = [0.89, 5.00, 9.10]

    for i, cx in enumerate(col_x):
        card = cards[i] if i < len(cards) else {}

        # Panel (modest rounding — rounded rect, not circle)
        add_rect(slide, cx, 1.65, 3.68, 5.25, fill_hex=C["panel_bg"], corner_radius=2000)

        # Badge background
        add_rect(slide, cx + 0.16, 1.91, 0.42, 0.42, fill_hex=badge_bg, corner_radius=80000)
        # Badge number text
        num_str = str(card.get("number", f"0{i+1}"))
        if len(num_str) < 2:
            num_str = f"0{num_str}"
        add_text(slide, num_str, cx + 0.17, 1.99, 0.42, 0.25,
                 font_name="Calibri", font_size=9, bold=True, color_hex=badge_num_color,
                 align=PP_ALIGN.CENTER)

        # Title
        title = card.get("title", card.get("label", ""))
        add_text(slide, title, cx + 0.66, 1.94, 2.94, 0.34,
                 font_name="Calibri", font_size=14, bold=title_bold, color_hex=title_color, word_wrap=True)

        # Divider
        add_rect(slide, cx + 0.16, 2.54, 3.36, 0.01, fill_hex=C["divider"])

        # Body bullets — merged into a single textbox (prevents fixed-y overflow gaps)
        bullets = card.get("bullets", [])
        bullet_lines = "\n\n".join(b.lstrip("- •").strip() for b in bullets if b.strip())
        add_markdown_text(slide, bullet_lines, cx + 0.16, 2.83, 3.35, 3.10,
                          font_name="Calibri Light", font_size=11, color_hex=C["text_body"], word_wrap=True,
                          native_bullets=True)

        # Footer
        footer = card.get("footer", "")
        add_rect(slide, cx + 0.16, 6.07, 3.36, 0.42, fill_hex=footer_fill, corner_radius=2000)
        
        # Decide footer font size (Slide 3/4 footers use 11pt, findings/conclusions/strategy use 9pt)
        # We can look at the slide's layout or the title_color to distinguish Slide 3 from others
        is_slide3_or_4 = (title_color == C["text_primary"] and not title_bold) or "FRAMEWORK" in str(slide_data.get("layout", ""))
        footer_size = 11 if is_slide3_or_4 else 9
        
        add_markdown_text(slide, footer, cx + 0.22, 6.12, 3.24, 0.32,
                          font_name="Calibri Light", font_size=footer_size, italic=True, color_hex=footer_text_color, word_wrap=True)

    return slide


def build_findings_overview(prs, blank_layout, slide_data: dict):
    """FINDINGS_OVERVIEW — 3 cards, no chart, red badges."""
    return _three_col_cards(
        prs, blank_layout, slide_data,
        badge_bg       = C["red_light"],
        badge_num_color= C["red"],
        title_color    = C["text_primary"],
        title_bold     = True,
        footer_fill    = C["red_light"],
        footer_text_color = C["red"],
    )


def build_conclusions_overview(prs, blank_layout, slide_data: dict):
    """CONCLUSIONS_OVERVIEW — identical positions to FINDINGS_OVERVIEW, blue."""
    return _three_col_cards(
        prs, blank_layout, slide_data,
        badge_bg       = C["blue"],
        badge_num_color= C["white"],
        title_color    = C["blue"],
        title_bold     = False,
        footer_fill    = C["blue_light"],
        footer_text_color = C["blue"],
    )


def build_strategy_maps(prs, blank_layout, slide_data: dict):
    """STRATEGY_MAPS — identical positions to FINDINGS_OVERVIEW, teal."""
    return _three_col_cards(
        prs, blank_layout, slide_data,
        badge_bg       = C["teal"],
        badge_num_color= C["white"],
        title_color    = C["teal"],
        title_bold     = False,
        footer_fill    = C["teal_light"],
        footer_text_color = C["teal"],
    )


def build_framework_3col(prs, blank_layout, slide_data: dict):
    """FRAMEWORK_3COL — 3 white panels with blue numbered badges."""
    slide = add_slide(prs, blank_layout)
    _standard_header(slide, slide_data)

    content = slide_data.get("content", {})
    cards = content.get("cards", content.get("columns", slide_data.get("cards", [])))
    col_x = [0.89, 5.00, 9.10]

    for i, cx in enumerate(col_x):
        card = cards[i] if i < len(cards) else {}

        # Panel (modest rounding — rounded rect, not circle)
        add_rect(slide, cx, 1.73, 3.53, 5.11, fill_hex=C["panel_bg"], corner_radius=2000)

        # Badge
        num_str = str(card.get("number", f"0{i+1}"))
        if len(num_str) < 2:
            num_str = f"0{num_str}"
        add_rect(slide, cx + 0.27, 1.96, 0.48, 0.45, fill_hex=C["blue"], corner_radius=80000)
        add_text(slide, num_str, cx + 0.27, 1.96, 0.48, 0.45,
                 font_name="Calibri", font_size=12, bold=True, color_hex=C["white"], align=PP_ALIGN.CENTER)

        # Title
        title = card.get("title", card.get("label", ""))
        add_text(slide, title, cx + 0.22, 2.54, 3.10, 0.34,
                 font_name="Calibri", font_size=14, bold=True, color_hex=C["text_primary"], word_wrap=True)

        # Body (bullets joined or body text)
        bullets = card.get("bullets", [])
        body_text = card.get("body", "\n\n".join(b.strip() for b in bullets if b.strip()))
        add_markdown_text(slide, body_text, cx + 0.22, 2.99, 3.10, 2.80,
                          font_name="Calibri Light", font_size=11, color_hex=C["text_body"], word_wrap=True,
                          native_bullets=True)

        # Footer
        footer = card.get("footer", "")
        footer_display = f"→ {footer}" if footer and not footer.startswith("→") else footer
        add_markdown_text(slide, footer_display, cx + 0.22, 6.15, 3.10, 0.47,
                          font_name="Calibri Light", font_size=11, italic=True, color_hex=C["text_muted"], word_wrap=True)

    return slide


def _estimate_cell_lines(text: str, col_width_inches: float, font_size_pt: float = 10) -> int:
    """Estimate number of wrapped lines for a cell given column width and font size.
    Uses average character width approximation: ~0.011" per pt per char (Calibri)."""
    if not text:
        return 1
    chars_per_line = max(1, int(col_width_inches / (font_size_pt * 0.011)))
    lines = 0
    for paragraph in text.split("\n"):
        words = paragraph.split()
        if not words:
            lines += 1
            continue
        current = 0
        for word in words:
            if current + len(word) + 1 > chars_per_line:
                lines += 1
                current = len(word)
            else:
                current += len(word) + 1
        lines += 1
    return max(1, lines)


def build_recs_table(prs, blank_layout, slide_data: dict):
    """RECS_TABLE — full-width recommendations table with dynamic row heights."""
    slide = add_slide(prs, blank_layout)
    _standard_header(slide, slide_data)

    content = slide_data.get("content", {})
    rows = content.get("rows", content.get("recommendations", slide_data.get("rows", [])))

    # Column widths (inches): PRIORITY | ACTION | OWNER | TIMELINE | EXPECTED IMPACT | SUCCESS METRIC
    col_widths  = [1.2,  4.0,    1.5,    1.2,      2.0,             1.66]
    col_headers = ["PRIORITY", "ACTION", "OWNER", "TIMELINE", "EXPECTED IMPACT", "SUCCESS METRIC"]
    font_size   = 10
    table_x     = 1.05
    header_y    = 1.76
    header_h    = 0.35
    line_h      = 0.175   # height per line at 10pt
    cell_pad_v  = 0.12    # top + bottom padding inside each cell
    min_row_h   = 0.42    # never shorter than this

    # Priority colour rules
    def priority_style(val: str) -> tuple[str | None, str, bool]:
        v = str(val).upper()
        if "P1-NOW" in v or "P1 NOW" in v:
            return C["red"], C["white"], True
        if "P1-30D" in v or "P1 30D" in v or "P1-30" in v:
            return C["orange"], C["white"], True
        return None, C["text_body"], False

    # Header row
    add_rect(slide, table_x, header_y, sum(col_widths), header_h, fill_hex=C["teal"])
    x_cur = table_x
    for hdr, cw in zip(col_headers, col_widths):
        add_text(slide, hdr, x_cur + 0.05, header_y + 0.07, cw - 0.10, header_h - 0.08,
                 font_name="Calibri", font_size=font_size, bold=True, color_hex=C["white"])
        x_cur += cw

    # Pre-compute dynamic height for every row
    def get_row_cells(row):
        return [
            row.get("priority",       row.get("Priority",       "")),
            row.get("action",         row.get("Action",         "")),
            row.get("owner",          row.get("Owner",          "")),
            row.get("timeline",       row.get("Timeline",       "")),
            row.get("expected_impact",row.get("impact",  row.get("Impact", ""))),
            row.get("success_metric", row.get("metric",  row.get("Metric", ""))),
        ]

    def compute_row_h(cells):
        usable_widths = [max(0.1, cw - 0.10) for cw in col_widths]
        max_lines = max(
            _estimate_cell_lines(str(v), uw, font_size)
            for v, uw in zip(cells, usable_widths)
        )
        return max(min_row_h, max_lines * line_h + cell_pad_v)

    # Body rows — dynamic height
    row_y = header_y + header_h
    for ri, row in enumerate(rows):
        cells = get_row_cells(row)
        row_h = compute_row_h(cells)
        row_bg = C["panel_bg"] if ri % 2 == 0 else C["content_bg"]
        add_rect(slide, table_x, row_y, sum(col_widths), row_h, fill_hex=row_bg)

        x_cur = table_x
        for ci, (cell_val, cw) in enumerate(zip(cells, col_widths)):
            cell_text = str(cell_val)

            if ci == 0:
                fill_col, text_col, is_bold = priority_style(cell_text)
                if fill_col:
                    add_rect(slide, x_cur + 0.03, row_y + 0.04,
                             cw - 0.06, row_h - 0.08, fill_hex=fill_col, corner_radius=10000)
                    add_text(slide, cell_text,
                             x_cur + 0.05, row_y + 0.07, cw - 0.10, row_h - 0.10,
                             font_name="Calibri", font_size=font_size, bold=is_bold,
                             color_hex=text_col, word_wrap=True)
                else:
                    add_text(slide, cell_text,
                             x_cur + 0.05, row_y + 0.07, cw - 0.10, row_h - 0.10,
                             font_name="Calibri", font_size=font_size, bold=False,
                             color_hex=C["text_body"], word_wrap=True)
            else:
                add_text(slide, cell_text,
                         x_cur + 0.05, row_y + 0.07, cw - 0.10, row_h - 0.10,
                         font_name="Calibri", font_size=font_size,
                         color_hex=C["text_body"], word_wrap=True)
            x_cur += cw

        row_y += row_h  # advance Y by actual row height

    return slide


def build_impact_two_col(prs, blank_layout, slide_data: dict):
    """IMPACT_TWO_COL — 2-column teal outcome panels."""
    slide = add_slide(prs, blank_layout)
    _standard_header(slide, slide_data)

    content = slide_data.get("content", {})
    left_data  = slide_data.get("left_panel",  content.get("left_panel",  {}))
    right_data = slide_data.get("right_panel", content.get("right_panel", {}))

    panel_specs = [
        (left_data,  0.90),
        (right_data, 6.82),
    ]

    for panel_data, px in panel_specs:
        if not panel_data:
            continue

        # Panel
        add_rect(slide, px, 1.65, 5.62, 5.25, fill_hex=C["panel_bg"], corner_radius=2000)

        # Badge
        add_rect(slide, px + 0.15, 1.91, 0.42, 0.42, fill_hex=C["teal"], corner_radius=80000)
        num_str = panel_data.get("number", "01" if px < 5 else "02")
        add_text(slide, str(num_str), px + 0.15, 1.99, 0.42, 0.25,
                 font_name="Calibri", font_size=9, bold=True, color_hex=C["white"], align=PP_ALIGN.CENTER)

        # Title
        title = panel_data.get("title", panel_data.get("chart_title", ""))
        add_text(slide, title, px + 0.49, 1.97, 4.80, 0.40,
                 font_name="Calibri", font_size=14, bold=True, color_hex=C["teal"], word_wrap=True)

        # Divider
        add_rect(slide, px + 0.18, 2.54, 4.92, 0.01, fill_hex=C["divider"])

        # Bullets — merged into a single textbox
        bullets = panel_data.get("bullets", [])
        if not bullets:
            raw = panel_data.get("supporting_text", panel_data.get("body", ""))
            bullets = [line.lstrip("•-– ").strip() for line in raw.split("\n") if line.strip()]

        all_text = "\n".join(b.strip() for b in bullets if b.strip())
        add_markdown_text(slide, all_text, px + 0.16, 2.83, 5.10, 3.50,
                          font_name="Calibri Light", font_size=12, color_hex=C["text_body"], word_wrap=True)

    return slide


def build_four_2x2(prs, blank_layout, slide_data: dict):
    """FOUR_2x2 — 2×2 grid of methodology/appendix panels."""
    slide = add_slide(prs, blank_layout)
    _standard_header(slide, slide_data)

    content = slide_data.get("content", {})
    panels_data = content.get("panels", content.get("cards", []))

    positions = [
        (0.89, 1.59, 5.60, 2.43, 1.03),
        (6.80, 1.59, 5.64, 2.43, 6.94),
        (0.89, 4.26, 5.60, 2.43, 1.03),
        (6.80, 4.26, 5.64, 2.43, 6.94),
    ]

    for idx, (px, py, pw, ph, tx) in enumerate(positions):
        panel = panels_data[idx] if idx < len(panels_data) else {}
        add_rect(slide, px, py, pw, ph, fill_hex=C["panel_bg"], corner_radius=2000)

        section_label = panel.get("label", panel.get("section", ""))
        title = panel.get("title", "")
        body = panel.get("body", "\n\n".join(b.strip() for b in panel.get("bullets", []) if b.strip()))
        footer = panel.get("footer", "")
        footer_display = f"→ {footer}" if footer and not footer.startswith("→") else footer

        add_text(slide, section_label, tx, py + 0.18, pw - 0.20, 0.25,
                 font_name="Calibri", font_size=9.5, bold=True, color_hex=C["blue"])
        add_text(slide, title, tx, py + 0.43, pw - 0.20, 0.30,
                 font_name="Calibri", font_size=12.5, bold=True, color_hex=C["text_primary"])
        add_markdown_text(slide, body, tx, py + 0.74, pw - 0.20, 1.20,
                          font_name="Calibri Light", font_size=11, color_hex=C["text_body"], word_wrap=True)
        add_markdown_text(slide, footer_display, tx, py + 2.04, pw - 0.20, 0.30,
                          font_name="Calibri Light", font_size=11, italic=True, color_hex=C["text_muted"])

    return slide


# ---------------------------------------------------------------------------
# Layout dispatcher
# ---------------------------------------------------------------------------
LAYOUT_BUILDERS = {
    "COVER":               build_cover,
    "BACKGROUND":          build_background,
    "INSIGHT_CHART":       build_insight_chart,
    "FINDINGS_OVERVIEW":   build_findings_overview,
    "CONCLUSIONS_OVERVIEW":build_conclusions_overview,
    "STRATEGY_MAPS":       build_strategy_maps,
    "FRAMEWORK_3COL":      build_framework_3col,
    "RECS_TABLE":          build_recs_table,
    "IMPACT_TWO_COL":      build_impact_two_col,
    "FOUR_2x2":            build_four_2x2,
    # Legacy aliases — old schema names
    "INSIGHT_FULL":           build_insight_chart,
    "INSIGHT_SPLIT":          build_insight_chart,
    "TWO_INSIGHT_COLS":       build_insight_chart,
    "THREE_CARDS":            build_findings_overview,
    "METHODOLOGY":            build_four_2x2,
    # Old freeform layout names (generated by ad-hoc LLM runs)
    "TITLE":                  build_cover,
    "EXECUTIVE_SUMMARY":      build_findings_overview,
    "KPIS":                   build_insight_chart,
    "TREND_CHART":            build_insight_chart,
    "REGIONAL_COMPARISON":    build_insight_chart,
    "DIAGNOSTIC":             build_findings_overview,
    "APAC_DEEP_DIVE":         build_insight_chart,
    "SEGMENT_ANALYSIS":       build_insight_chart,
    "FORECAST":               build_insight_chart,
    "RECOMMENDATIONS":        build_recs_table,
}

_FALLBACK_LAYOUT = "INSIGHT_CHART"


# ---------------------------------------------------------------------------
# Main build function
# ---------------------------------------------------------------------------
def build_pptx(stem: str, output_path: str | None = None, run_id: str | None = None,
               force: bool = False):
    """
    Read story_arc.json + chart_images.json for *stem*, build slidedeck.pptx.

    Args:
        stem:        Dataset stem, e.g. 'sales_orders_2023_2026'
        output_path: Override output file path (optional)
        run_id:      Pipeline run ID for tracing (auto-generated if None)
    """
    import re
    global _chart_map, _chart_dir

    # CP6 — Sanitize stem: allow only alphanumeric, hyphens, underscores, dots
    if not re.match(r'^[\w\-\.]+$', stem):
        raise ValueError(f"Invalid stem '{stem}': must contain only alphanumeric, hyphens, underscores, dots")

    run_id = run_id or new_run_id()
    log = get_logger(__name__, run_id=run_id, stem=stem)

    pipeline = PIPELINE_DIR(stem)
    arc_path = pipeline / "story_arc.json"

    if not arc_path.exists():
        log.error("story_arc_missing", path=str(arc_path))
        sys.exit(1)

    with open(arc_path, encoding="utf-8") as f:
        arc = json.load(f)

    # CP2 — Validate required story_arc.json fields
    _schema_errors: list[str] = []
    if "slides" not in arc or not isinstance(arc["slides"], list):
        _schema_errors.append("missing or invalid 'slides' key (must be a list)")
    else:
        if len(arc["slides"]) == 0:
            _schema_errors.append("'slides' list is empty")
        for _i, _s in enumerate(arc["slides"]):
            if not isinstance(_s, dict):
                _schema_errors.append(f"slides[{_i}] is not an object")
            elif "layout" not in _s:
                _schema_errors.append(f"slides[{_i}] missing required 'layout' field")
    if _schema_errors:
        for _err in _schema_errors:
            log.error("story_arc_invalid", reason=_err)
        sys.exit(1)

    # Load chart_images.json (optional) and scan chart folders
    _chart_map = {}
    chart_images_path = pipeline / "chart_images.json"
    if chart_images_path.exists():
        with open(chart_images_path, encoding="utf-8") as f:
            ci = json.load(f)
            for c in ci.get("charts", []):
                cid = c.get("chart_id", "")
                fname = c.get("filename", "")
                if cid and fname:
                    _chart_map[cid] = pipeline / "chart_images" / fname
    # Scan all chart image folders as fallback
    for folder_name in ("chart_images", "charts"):
        folder = pipeline / folder_name
        if folder.exists():
            for img in folder.glob("*.png"):
                if img.stem not in _chart_map:
                    _chart_map[img.stem] = img
    _chart_dir = pipeline / "chart_images"

    # Determine output path
    if output_path:
        out = Path(output_path)
    else:
        report_type = arc.get("report_type", arc.get("type", stem.split("_")[0]))
        out_dir = REPORTS_DIR(stem, report_type)
        out_dir.mkdir(parents=True, exist_ok=True)
        out = out_dir / "slidedeck.pptx"
    out.parent.mkdir(parents=True, exist_ok=True)

    # CP3 / CP8 — Idempotency + HITL: skip or confirm before overwriting
    if out.exists():
        if not force:
            log.info("output_exists_skip", path=str(out),
                     hint="pass force=True or --force to overwrite")
            print(f"  Output already exists, skipping: {out}")
            print(f"  Run with --force to overwrite.")
            return str(out)
        # force=True: ask for confirmation in interactive mode (HITL)
        if sys.stdin.isatty():
            answer = input(f"  [HITL] Overwrite existing file? {out} [y/N] ").strip().lower()
            if answer not in ("y", "yes"):
                log.info("output_overwrite_cancelled", path=str(out))
                print("  Cancelled.")
                return str(out)
        log.warning("output_overwrite", path=str(out), forced=True)

    # Initialise presentation from template
    prs, blank_layout = init_presentation()

    slides = arc.get("slides", [])
    log.info("build_start", slide_count=len(slides), output=str(out))

    errors = []
    for i, slide_data in enumerate(slides):
        slide_data["_stem"] = stem
        layout = slide_data.get("layout") or slide_data.get("type") or _FALLBACK_LAYOUT
        layout = layout.upper().replace(" ", "_")

        builder = LAYOUT_BUILDERS.get(layout)
        if builder is None:
            log.warning("unknown_layout", slide=i+1, layout=layout, fallback=_FALLBACK_LAYOUT)
            builder = LAYOUT_BUILDERS[_FALLBACK_LAYOUT]

        num = slide_data.get("slide_number", i + 1)
        headline = slide_data.get("headline", "")[:70]
        # Keep stdout for human-readable progress (consistent with existing UX)
        print(f"  [{num}] {layout:<22} {headline}")
        log.debug("slide_build", slide=num, layout=layout)

        try:
            built_slide = builder(prs, blank_layout, slide_data)
            if built_slide is not None:
                clear_slide_shadows(built_slide)
        except Exception as exc:
            log.error("slide_render_error", slide=num, layout=layout, error=str(exc))
            traceback.print_exc()
            errors.append({"slide": num, "layout": layout, "error": str(exc)})
            try:
                err_slide = add_slide(prs, blank_layout)
                add_bg(err_slide)
                add_text(err_slide,
                         f"[Slide {num} — render error: {layout}]",
                         0.89, 0.68, 11.56, 0.77,
                         font_size=20, bold=True, color_hex=C["red"])
            except Exception as e2:
                log.debug("error_slide_failed", slide=num, error=str(e2))

    prs.save(str(out))
    size_kb = os.path.getsize(str(out)) / 1024
    log.info("build_complete", output=str(out), size_kb=round(size_kb, 1),
             slide_count=len(slides), error_count=len(errors))
    print(f"Saved: {out} ({size_kb:.1f} KB)")
    return str(out)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="AI Analyst — deterministic PPTX builder v3"
    )
    parser.add_argument("--stem", required=True,
                        help="Dataset stem, e.g. sales_orders_2023_2026")
    parser.add_argument("--output", default=None,
                        help="Override output .pptx path")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite existing output file (default: skip if exists)")
    args = parser.parse_args()
    build_pptx(args.stem, args.output, force=args.force)
