"""
send_summary.py
---------------
Đọc stock_data.csv, tính metrics cơ bản, gửi email tóm tắt qua Gmail SMTP.
Chạy sau fetch_stock.py trong GitHub Actions.
"""

import csv
import os
import smtplib
import sys
from collections import defaultdict
from datetime import date, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import yaml

# ─── CONFIG ──────────────────────────────────────────────────────────────────

_config = yaml.safe_load(Path("config.yaml").read_text(encoding="utf-8"))
TICKERS = _config["tickers"]
TOP_N = _config["report"].get("top_picks", 3)

DATA_FILE = Path("data/stock_data.csv")

GMAIL_USER = os.environ["GMAIL_USER"]          # set trong GitHub Secrets
GMAIL_PASSWORD = os.environ["GMAIL_APP_PASSWORD"]  # set trong GitHub Secrets
EMAIL_TO = os.environ.get("EMAIL_TO", GMAIL_USER)

TODAY = date.today().strftime("%Y-%m-%d")
SUBJECT = f"VN Stock Briefing — {TODAY}"

# ─── ĐỌC DATA ────────────────────────────────────────────────────────────────

def read_csv():
    data = defaultdict(list)
    with open(DATA_FILE, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            data[row["Ticker"]].append({
                "date": row["Date"],
                "close": float(row["Close"]) if row["Close"] else None,
                "volume": float(row["Volume"]) if row["Volume"] else None,
            })
    # Sort theo ngày
    for ticker in data:
        data[ticker].sort(key=lambda x: x["date"])
    return data

# ─── TÍNH METRICS ────────────────────────────────────────────────────────────

def compute_metrics(data):
    cutoff = (date.today() - timedelta(days=30)).strftime("%Y-%m-%d")
    results = []

    for ticker in TICKERS:
        rows = [r for r in data.get(ticker, []) if r["close"] is not None]
        rows_30d = [r for r in rows if r["date"] >= cutoff]

        if len(rows_30d) < 2:
            continue

        close_start = rows_30d[0]["close"]
        close_end = rows_30d[-1]["close"]
        return_30d = (close_end - close_start) / close_start * 100

        # Volatility (std of daily returns)
        closes = [r["close"] for r in rows_30d]
        daily_returns = [(closes[i] - closes[i-1]) / closes[i-1] * 100
                         for i in range(1, len(closes))]
        avg = sum(daily_returns) / len(daily_returns)
        variance = sum((x - avg) ** 2 for x in daily_returns) / len(daily_returns)
        volatility = variance ** 0.5

        # Trend
        if return_30d > 3:
            trend = "↑ Tăng"
        elif return_30d < -3:
            trend = "↓ Giảm"
        else:
            trend = "→ Sideway"

        # Score = return / volatility (risk-adjusted)
        score = return_30d / volatility if volatility > 0 else 0

        results.append({
            "ticker": ticker,
            "return_30d": return_30d,
            "volatility": volatility,
            "trend": trend,
            "score": score,
            "close": close_end,
        })

    results.sort(key=lambda x: x["score"], reverse=True)
    return results

# ─── TẠO EMAIL ───────────────────────────────────────────────────────────────

def build_email(metrics):
    top = metrics[:TOP_N]
    bottom = metrics[-2:] if len(metrics) >= 5 else []

    lines = [
        f"<h2>VN Stock Briefing — {TODAY}</h2>",
        "<h3>📊 Tổng quan 10 mã</h3>",
        "<table border='1' cellpadding='6' cellspacing='0' style='border-collapse:collapse;font-family:Arial;font-size:13px'>",
        "<tr style='background:#f0f0f0'><th>Mã</th><th>Return 30D</th><th>Volatility</th><th>Trend</th></tr>",
    ]

    for m in metrics:
        color = "#d4edda" if m["score"] > 0 else "#f8d7da"
        lines.append(
            f"<tr style='background:{color}'>"
            f"<td><b>{m['ticker']}</b></td>"
            f"<td>{m['return_30d']:+.1f}%</td>"
            f"<td>{m['volatility']:.1f}%</td>"
            f"<td>{m['trend']}</td>"
            f"</tr>"
        )

    lines.append("</table>")

    lines.append(f"<h3>✅ Top {TOP_N} nên xem xét</h3><ul>")
    for m in top:
        lines.append(
            f"<li><b>{m['ticker']}</b> — Return 30D: {m['return_30d']:+.1f}%, "
            f"Volatility: {m['volatility']:.1f}%, Trend: {m['trend']}</li>"
        )
    lines.append("</ul>")

    if bottom:
        lines.append("<h3>❌ Cần thận trọng</h3><ul>")
        for m in bottom:
            lines.append(
                f"<li><b>{m['ticker']}</b> — Return 30D: {m['return_30d']:+.1f}%, "
                f"Trend: {m['trend']}</li>"
            )
        lines.append("</ul>")

    lines.append("<p style='color:gray;font-size:11px'>Auto-generated by VN Stock Pipeline</p>")
    return "\n".join(lines)

# ─── GỬI EMAIL ───────────────────────────────────────────────────────────────

def send_email(html_body):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = SUBJECT
    msg["From"] = GMAIL_USER
    msg["To"] = EMAIL_TO
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(GMAIL_USER, GMAIL_PASSWORD)
        server.sendmail(GMAIL_USER, EMAIL_TO, msg.as_string())

    print(f"✓ Email gửi thành công đến {EMAIL_TO}")

# ─── MAIN ────────────────────────────────────────────────────────────────────

def get_latest_report() -> Path | None:
    """Tìm report HTML mới nhất trong vòng 3 ngày gần nhất."""
    reports_dir = Path("data/reports")
    if not reports_dir.exists():
        return None
    cutoff = date.today() - timedelta(days=3)
    candidates = []
    for f in reports_dir.glob("*.html"):
        # Lấy ngày từ tên file (pattern: *YYYY-MM-DD*.html)
        for part in f.stem.split("_"):
            try:
                file_date = date.fromisoformat(part)
                if file_date >= cutoff:
                    candidates.append((file_date, f))
                break
            except ValueError:
                continue
    if not candidates:
        return None
    # Trả về file có ngày mới nhất
    candidates.sort(key=lambda x: x[0], reverse=True)
    return candidates[0][1]


if __name__ == "__main__":
    # Check 1: data tồn tại không
    if not DATA_FILE.exists():
        print("Không tìm thấy stock_data.csv. Bỏ qua gửi email.")
        sys.exit(0)

    # Check 2: có report trong 3 ngày gần nhất không
    latest_report = get_latest_report()
    if latest_report is None:
        print("Không tìm thấy report HTML trong 3 ngày gần nhất. Bỏ qua gửi email.")
        sys.exit(0)
    print(f"Dùng report: {latest_report.name}")

    data = read_csv()
    metrics = compute_metrics(data)

    if not metrics:
        print("Không đủ data để tính metrics. Bỏ qua.")
        sys.exit(0)

    html = build_email(metrics)
    send_email(html)
